# Change the application's port
server:
  port: 8002

# Inject some property into the controller
app:
  service:
    name: Eureka Client Example (Default profile)
    icon: 128049

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: app.1
    bootstrap-servers: 5.141.84.146:9092
    client-id: client1
    template:
      default-topic: jmtopic2
    producer:
      bootstrap-servers: 5.141.84.146:9092